spring:
  application:
    name: starter
  cloud:
    kubernetes:
      enabled: true
      discovery:
        enabled: true
    kubernetes:
      config:
        enabled: false

server:
  port: 8080

# Jaeger Config
spring:
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    enabled: false
  jaeger:
    enabled: true
    service-name: ${spring.application.name}
    udp-sender:
      host: jaeger-agent
      port: 6831

# Log Config
logging:
  level:
    com.example: DEBUG

